module.exports = {
  apps: [
    {
      name: 'audnix-api-gateway',
      script: './services/api-gateway/api-only.ts',
      interpreter: 'node',
      interpreter_args: '--require ./polyfill-file.cjs --import tsx --import ./instrument.ts',
      instances: 1,
      exec_mode: 'fork',
      dotenv: '.env',
      env: {
        NODE_ENV: 'production',
        NEW_EMAIL_BACKEND: 'rust',
        APP_ROLE: 'api',
        PORT: 5000,
        API_DISABLE_SOCKET: 'true',
        DISABLE_STATIC_SERVE: 'true',
        S3_REGION: 'us-east-1'
      },
      error_file: './logs/api-error.log',
      out_file: './logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '1G'
    },
    {
      name: 'audnix-socket-server',
      script: './services/socket-service/index.ts',
      interpreter: 'node',
      interpreter_args: '--require ./polyfill-file.cjs --import tsx --import ./instrument.ts',
      instances: 1,
      exec_mode: 'fork',
      dotenv: '.env',
      env: {
        NODE_ENV: 'production',
        NEW_EMAIL_BACKEND: 'rust',
        APP_ROLE: 'socket',
        PORT: 5001,
        S3_REGION: 'us-east-1'
      },
      error_file: './logs/socket-error.log',
      out_file: './logs/socket-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '512M'
    },
    {
      name: 'audnix-worker-email',
      script: './services/email-service/index.ts',
      interpreter: 'node',
      interpreter_args: '--require ./polyfill-file.cjs --import tsx --import ./instrument.ts',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        NEW_EMAIL_BACKEND: 'rust',
        APP_ROLE: 'email',
        REDIS_URL: 'redis://:devpassword@127.0.0.1:6379'
      },
      error_file: './logs/email-error.log',
      out_file: './logs/email-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '1G'
    },
    {
      name: 'audnix-worker-imap',
      script: './services/email-worker/src/index.ts',
      interpreter: 'node',
      interpreter_args: '--require ./polyfill-file.cjs --import tsx --import ./instrument.ts',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        NEW_EMAIL_BACKEND: 'rust',
        APP_ROLE: 'imap',
        REDIS_URL: 'redis://:devpassword@127.0.0.1:6379',
        DATABASE_URL_POOL: 'postgresql://postgres:44L8h5adNgVuAzr@database-1.cuns46ao86xu.us-east-1.rds.amazonaws.com:5432/postgres?sslmode=no-verify'
      },
      error_file: './logs/imap-error.log',
      out_file: './logs/imap-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '512M'
    },
    {
      name: 'audnix-worker-ai',
      script: './services/brain-worker/index.ts',
      interpreter: 'node',
      interpreter_args: '--require ./polyfill-file.cjs --import tsx --import ./instrument.ts',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        NEW_EMAIL_BACKEND: 'rust',
        APP_ROLE: 'ai',
        REDIS_URL: 'redis://:devpassword@127.0.0.1:6379'
      },
      error_file: './logs/ai-error.log',
      out_file: './logs/ai-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '2G'
    },
    {
      name: 'audnix-worker-outreach',
      script: './services/outreach-worker/index.ts',
      interpreter: 'node',
      interpreter_args: '--require ./polyfill-file.cjs --import tsx --import ./instrument.ts',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        NEW_EMAIL_BACKEND: 'rust',
        APP_ROLE: 'outreach',
        REDIS_URL: 'redis://:devpassword@127.0.0.1:6379'
      },
      error_file: './logs/outreach-error.log',
      out_file: './logs/outreach-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '2G'
    },
    {
      name: 'audnix-worker-lead-recovery',
      script: './services/lead-recovery-worker/index.ts',
      interpreter: 'node',
      interpreter_args: '--require ./polyfill-file.cjs --import tsx --import ./instrument.ts',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        NEW_EMAIL_BACKEND: 'rust',
        APP_ROLE: 'lead-recovery',
        REDIS_URL: 'redis://:devpassword@127.0.0.1:6379',
        MYSQL_HOST: 'database-3.cuns46ao86xu.us-east-1.rds.amazonaws.com',
        MYSQL_USER: 'admin',
        MYSQL_PASSWORD: 'TrexJetTechnology2008!.',
        MYSQL_DATABASE: 'lead_recovery'
      },
      error_file: './logs/lead-recovery-error.log',
      out_file: './logs/lead-recovery-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '1G'
    },
    {
      name: 'audnix-worker-social',
      script: './services/social-worker/src/social/index.ts',
      interpreter: 'node',
      interpreter_args: '--require ./polyfill-file.cjs --import tsx --import ./instrument.ts',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        NEW_EMAIL_BACKEND: 'rust',
        APP_ROLE: 'social',
        REDIS_URL: 'redis://:devpassword@127.0.0.1:6379'
      },
      error_file: './logs/social-error.log',
      out_file: './logs/social-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '512M'
    },
    {
      name: 'audnix-worker-billing',
      script: './services/billing-service/src/billing/index.ts',
      interpreter: 'node',
      interpreter_args: '--require ./polyfill-file.cjs --import tsx --import ./instrument.ts',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        NEW_EMAIL_BACKEND: 'rust',
        APP_ROLE: 'billing',
        REDIS_URL: 'redis://:devpassword@127.0.0.1:6379'
      },
      error_file: './logs/billing-error.log',
      out_file: './logs/billing-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '512M'
    },
    {
      name: 'audnix-worker-orchestrator',
      script: './services/brain-worker/src/orchestrator/index.ts',
      interpreter: 'node',
      interpreter_args: '--require ./polyfill-file.cjs --import tsx --import ./instrument.ts',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        NEW_EMAIL_BACKEND: 'rust',
        APP_ROLE: 'orchestrator',
        REDIS_URL: 'redis://:devpassword@127.0.0.1:6379'
      },
      error_file: './logs/orchestrator-error.log',
      out_file: './logs/orchestrator-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '1G'
    },
    {
      name: 'audnix-worker-rag',
      script: './services/rag-worker/index.ts',
      interpreter: 'node',
      interpreter_args: '--require ./polyfill-file.cjs --import tsx --import ./instrument.ts',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        NEW_EMAIL_BACKEND: 'rust',
        APP_ROLE: 'rag',
        REDIS_URL: 'redis://:devpassword@127.0.0.1:6379'
      },
      error_file: './logs/rag-error.log',
      out_file: './logs/rag-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '2G'
    },
    {
      name: 'audnix-worker-knowledge',
      script: './services/rag-worker/index.ts',
      interpreter: 'node',
      interpreter_args: '--require ./polyfill-file.cjs --import tsx --import ./instrument.ts',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        NEW_EMAIL_BACKEND: 'rust',
        APP_ROLE: 'knowledge',
        REDIS_URL: 'redis://:devpassword@127.0.0.1:6379'
      },
      error_file: './logs/knowledge-error.log',
      out_file: './logs/knowledge-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '2G'
    },
    {
      name: 'audnix-worker-audit',
      script: './shared/services/audit/index.ts',
      interpreter: 'node',
      interpreter_args: '--require ./polyfill-file.cjs --import tsx --import ./instrument.ts',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        NEW_EMAIL_BACKEND: 'rust',
        APP_ROLE: 'audit',
        REDIS_URL: 'redis://:devpassword@127.0.0.1:6379'
      },
      error_file: './logs/audit-error.log',
      out_file: './logs/audit-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '512M'
    },
    {
      name: 'audnix-worker-vectordb',
      script: './services/vector-db-service/index.ts',
      interpreter: 'node',
      interpreter_args: '--require ./polyfill-file.cjs --import tsx --import ./instrument.ts',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        NEW_EMAIL_BACKEND: 'rust',
        APP_ROLE: 'vectordb',
        REDIS_URL: 'redis://:devpassword@127.0.0.1:6379'
      },
      error_file: './logs/vectordb-error.log',
      out_file: './logs/vectordb-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '512M'
    },
    {
      name: 'audnix-worker-warmup',
      script: './services/warmup-service/index.ts',
      interpreter: 'node',
      interpreter_args: '--require ./polyfill-file.cjs --import tsx --import ./instrument.ts',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        NEW_EMAIL_BACKEND: 'rust',
        APP_ROLE: 'warmup',
        REDIS_URL: 'redis://:devpassword@127.0.0.1:6379'
      },
      error_file: './logs/warmup-error.log',
      out_file: './logs/warmup-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '512M'
    },
    {
      name: 'audnix-deliverability',
      script: './services/deliverability-service/dist/index.js',
      instances: 1,
      exec_mode: 'fork',
      dotenv: '.env',
      env_file: './.env',
      env: {
        NODE_ENV: 'production',
        NEW_EMAIL_BACKEND: 'rust',
        APP_ROLE: 'deliverability',
        PORT: '3100'
      },
      error_file: './logs/deliverability-error.log',
      out_file: './logs/deliverability-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '256M'
    },
    {
      name: 'audnix-infra-scaler',
      script: './services/outreach-worker/src/outreach-lib/infra-scaler-entry.ts',
      interpreter: 'node',
      interpreter_args: '--require ./polyfill-file.cjs --import tsx --import ./instrument.ts',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        NEW_EMAIL_BACKEND: 'rust',
        APP_ROLE: 'infra-scaler',
        QUEUE_AUTOSCALER_ENABLED: 'true',
        REDIS_URL: 'redis://:devpassword@127.0.0.1:6379'
      },
      error_file: './logs/infra-scaler-error.log',
      out_file: './logs/infra-scaler-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '256M'
    },
    {
      name: 'audnix-rust-imap-worker',
      script: './rust-imap-worker/target/release/audnix-imap-worker',
      instances: 0,
      exec_mode: 'fork',
      env: {
        RUST_LOG: 'warn',
        REDIS_URL: 'redis://:devpassword@127.0.0.1:6379',
      },
      error_file: './logs/rust-imap-error.log',
      out_file: './logs/rust-imap-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'audnix-rust-email-sender',
      script: './rust-email-sender/target/release/audnix-email-sender',
      instances: 1,
      exec_mode: 'fork',
      env: {
        RUST_LOG: 'info',
        REDIS_URL: 'redis://:devpassword@127.0.0.1:6379',
        EMAIL_QUEUE_NAME: 'email-send-queue',
        EMAIL_RESULT_QUEUE_NAME: 'email-send-results',
        WORKER_COUNT: '4',
        MAX_CONCURRENT_SENDS: '100',
        SMTP_PORT: '587',
        SMTP_TIMEOUT_SECS: '15'
      },
      error_file: './logs/rust-email-error.log',
      out_file: './logs/rust-email-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    }
  ]
};
