/**
 * Disclaimer Generator
 * Auto-prepends legal disclaimers to AI-generated messages
 * Keeps disclaimers hidden from frontend but logged for compliance
 */

export interface DisclaimerConfig {
  channel: 'email' | 'voice';
  companyName?: string;
}

/**
 * Generate disclaimer for AI messages
 * Blends naturally into message to comply with legal requirements
 */
export function generateDisclaimerPrefix(config: DisclaimerConfig): string {
  const { channel, companyName = 'Audnix' } = config;

  // Different disclaimers for different channels
  // Keep them concise so they blend into the natural message
  const disclaimers: Record<string, string> = {
    email: `[Automated message from ${companyName} - This message was generated by AI to continue our conversation. For official policies and commitments, please refer to our full Terms of Service.]`,





    voice: `This is an automated message from ${companyName}. `, // Voice: subtle prefix to sound natural
  };

  return disclaimers[channel] || disclaimers.email;
}

/**
 * Get disclaimer for message (UI/internal use only)
 * DO NOT append to the actual message sent to leads, as requested by user.
 * This can be shown in the dashboard conversation view but remains hidden from leads.
 */
export function getMessageDisclaimer(
  channel: 'email' | 'voice',
  companyName?: string
): string {
  return generateDisclaimerPrefix({ channel, companyName });
}

/**
 * DEPRECATED: Prepend disclaimer to message
 * Now returns the original message unmodified to ensure leads don't see AI disclaimers,
 * while still providing the disclaimer string for the UI to display in gray/subtle text.
 */
export function prependDisclaimerToMessage(
  messageBody: string,
  channel: 'email' | 'voice',
  companyName?: string
): {
  messageWithDisclaimer: string;
  disclaimerPrefix: string;
} {
  const disclaimerPrefix = getMessageDisclaimer(channel, companyName);

  // Return the original message - DO NOT append the disclaimer
  // This satisfies the user's request that leads shouldn't know it's AI
  return {
    messageWithDisclaimer: messageBody,
    disclaimerPrefix,
  };
}

/**
 * Generate audit trail entry for disclaimer
 * Logs that a disclaimer was sent with this message
 */
export function createDisclaimerAuditEntry(messageId: string, channel: string) {
  return {
    actionType: 'disclaimer_included',
    channel,
    messageId,
    timestamp: new Date(),
    details: `Disclaimer prepended to ${channel} message for legal compliance`,
  };
}
