web: npm run start:api-gateway
socket: npm run start:socket-server
email_worker: npm run start:worker:email
imap_worker: npm run start:worker:imap
ai_worker: npm run start:worker:ai
outreach_worker: npm run start:worker:outreach
lead_recovery_worker: npm run start:worker:lead-recovery
social_worker: npm run start:worker:social
billing_worker: npm run start:worker:billing
orchestrator_worker: npm run start:worker:orchestrator
knowledge_worker: npm run start:worker:knowledge
audit_worker: npm run start:worker:audit
warmup_worker: npm run start:worker:warmup
infra_scaler: npm run start:infra:scaler
