// @ts-nocheck
/**
 * seed-content.ts
 *
 * Template seeding intentionally DISABLED.
 * All copy is generated by AI per user business context — no hardcoded templates.
 * Injecting generic templates overrides user personalization and degrades reply quality.
 *
 * To run any future seed scripts, create a new file in scripts/ with a specific purpose.
 */

console.log('ℹ️  [seed-content] Template seeding is disabled. No templates were inserted.');
process.exit(0);
