ALTER TABLE users ADD COLUMN IF NOT EXISTS calendar_link TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS timezone TEXT DEFAULT 'UTC';
ALTER TABLE users ADD COLUMN IF NOT EXISTS availability JSONB DEFAULT '[]';
ALTER TABLE users ADD COLUMN IF NOT EXISTS openai_api_key TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS sendgrid_api_key TEXT;
