-- Migration 027: Seed 110+ sales objections into content_library
-- Objections organized by category with intent tags for Email, Instagram, and Manual copy-paste
-- Uses NULL user_id for system-wide templates accessible to all users

-- First, add nullable user_id support for system templates if not already done
ALTER TABLE content_library ALTER COLUMN user_id DROP NOT NULL;

-- TIMING OBJECTIONS (15 entries)
INSERT INTO content_library (user_id, type, name, content, intent_tags, objection_tags, channel_restriction, metadata)
VALUES
  (NULL, 'objection', 'Timing - Not Right Now', 'I totally understand timing is everything. Quick question - if timing were perfect, would this be something you''d move forward with? Let''s at least lock in your spot so you don''t lose the current pricing.', '["timing", "hesitation"]'::jsonb, '["not_now", "busy", "later"]'::jsonb, 'all', '{"category": "timing", "reframe": "Turn delay into urgency"}'::jsonb),
  (NULL, 'objection', 'Timing - Too Busy', 'That actually makes this the perfect time - this system runs 24/7 so you don''t have to. It''s designed for busy people who can''t afford to miss opportunities. Want me to show you how it works while you sleep?', '["timing", "busy"]'::jsonb, '["busy", "no_time", "swamped"]'::jsonb, 'all', '{"category": "timing", "reframe": "Busy = more need for automation"}'::jsonb),
  (NULL, 'objection', 'Timing - End of Quarter', 'End of quarter is actually ideal - you can start fresh next quarter with leads already warmed up. Plus, starting now means results by Q1. Can we get you set up today?', '["timing", "business_cycle"]'::jsonb, '["quarter", "fiscal", "budget"]'::jsonb, 'all', '{"category": "timing", "reframe": "Leverage business cycles"}'::jsonb),
  (NULL, 'objection', 'Timing - Just Started New Project', 'Perfect timing actually - integrating now means your new project benefits from day one. The longer you wait, the more leads slip through. What if we did a quick setup call?', '["timing", "new_venture"]'::jsonb, '["new_project", "just_started", "beginning"]'::jsonb, 'all', '{"category": "timing", "reframe": "New = perfect integration point"}'::jsonb),
  (NULL, 'objection', 'Timing - After the Holidays', 'Here''s the thing - your competitors aren''t waiting. Starting now means you''re ahead when everyone else is still planning. Plus holiday season = more buying intent. Ready to get ahead?', '["timing", "seasonal"]'::jsonb, '["holiday", "new_year", "after"]'::jsonb, 'all', '{"category": "timing", "reframe": "Get ahead while others wait"}'::jsonb),
  (NULL, 'objection', 'Timing - Need to Think', 'Absolutely, big decisions deserve thought. What specific part would help to think through together? Often talking it out reveals the answer faster than mulling alone.', '["timing", "consideration"]'::jsonb, '["think", "consider", "need_time"]'::jsonb, 'all', '{"category": "timing", "reframe": "Thinking together beats thinking alone"}'::jsonb),
  (NULL, 'objection', 'Timing - Check Back Later', 'Happy to! But let me ask - what would need to change for this to be a yes? That way when we reconnect, I can address exactly what matters most to you.', '["timing", "follow_up"]'::jsonb, '["later", "follow_up", "check_back"]'::jsonb, 'all', '{"category": "timing", "reframe": "Qualify the real objection"}'::jsonb),
  (NULL, 'objection', 'Timing - Bad Time of Year', 'I hear you. Though interestingly, our most successful users started during "bad" times - less competition for attention, more time to optimize. What if we just explored fit today?', '["timing", "seasonal"]'::jsonb, '["bad_time", "slow_season", "year"]'::jsonb, 'all', '{"category": "timing", "reframe": "Bad times = opportunity"}'::jsonb),
  (NULL, 'objection', 'Timing - Already Committed Elsewhere', 'Totally understand loyalty. Quick thought - most of our users run us alongside existing tools, then transition when they see results. No commitment required to test. Sound fair?', '["timing", "commitment"]'::jsonb, '["committed", "already_using", "loyalty"]'::jsonb, 'all', '{"category": "timing", "reframe": "Parallel testing reduces risk"}'::jsonb),
  (NULL, 'objection', 'Timing - Wait for Next Version', 'Great instinct! But here''s insider info - current users get all updates free, plus you start building results now. Waiting means starting from zero later. Lock in now?', '["timing", "product"]'::jsonb, '["next_version", "update", "new_features"]'::jsonb, 'all', '{"category": "timing", "reframe": "Early adopters win long-term"}'::jsonb),
  (NULL, 'objection', 'Timing - Team is Overwhelmed', 'That''s exactly why this exists - to take work OFF your team''s plate, not add to it. Setup takes 10 minutes and then it runs itself. Can I show you the quick-start?', '["timing", "team"]'::jsonb, '["overwhelmed", "team_busy", "capacity"]'::jsonb, 'all', '{"category": "timing", "reframe": "Automation reduces overwhelm"}'::jsonb),
  (NULL, 'objection', 'Timing - Waiting for Funding', 'Smart planning. Quick math though - if this recovers just one deal, it pays for itself. Most users see ROI in week one. Could we do a results-first trial?', '["timing", "budget"]'::jsonb, '["funding", "investment", "capital"]'::jsonb, 'all', '{"category": "timing", "reframe": "ROI beats waiting for funding"}'::jsonb),
  (NULL, 'objection', 'Timing - Moving/Transitioning', 'Transitions are actually perfect for new systems - clean slate, fresh start. Plus this runs in background while you handle the move. 10-minute setup, then hands-free?', '["timing", "transition"]'::jsonb, '["moving", "transition", "change"]'::jsonb, 'all', '{"category": "timing", "reframe": "Transitions = clean slate opportunity"}'::jsonb),
  (NULL, 'objection', 'Timing - Need to Focus on Core', 'Exactly my point - this handles the follow-up so you CAN focus on core. It''s not adding work, it''s removing distraction. See how in 5 minutes?', '["timing", "focus"]'::jsonb, '["focus", "core", "priorities"]'::jsonb, 'all', '{"category": "timing", "reframe": "Automation enables focus"}'::jsonb),
  (NULL, 'objection', 'Timing - Personal Stuff Going On', 'I completely respect that - family and life come first. This is exactly the kind of tool that works when you can''t. It''ll be here when you''re ready. Can I check in next month?', '["timing", "personal"]'::jsonb, '["personal", "life", "family"]'::jsonb, 'all', '{"category": "timing", "reframe": "Empathy + future follow-up"}'::jsonb)
ON CONFLICT DO NOTHING;

-- PRICE OBJECTIONS (20 entries)
INSERT INTO content_library (user_id, type, name, content, intent_tags, objection_tags, channel_restriction, metadata)
VALUES
  (NULL, 'objection', 'Price - Too Expensive', 'I totally get it. Let me ask - expensive compared to what? The cost of one lost deal usually exceeds a full year with us. What''s a typical deal worth to you?', '["price", "value"]'::jsonb, '["expensive", "cost", "too_much"]'::jsonb, 'all', '{"category": "price", "reframe": "Compare to cost of inaction"}'::jsonb),
  (NULL, 'objection', 'Price - Can''t Afford It', 'Understood. But here''s the real question - can you afford NOT to have automated follow-up? Most businesses lose 40% of warm leads to poor follow-up. What''s that costing you?', '["price", "budget"]'::jsonb, '["afford", "budget", "money"]'::jsonb, 'all', '{"category": "price", "reframe": "Cost of not buying is higher"}'::jsonb),
  (NULL, 'objection', 'Price - Need Cheaper Option', 'We do have different tiers. But let me share something - our users who started with cheaper tools tell us they wasted months before switching. The ROI math matters more than the price tag.', '["price", "options"]'::jsonb, '["cheaper", "discount", "lower"]'::jsonb, 'all', '{"category": "price", "reframe": "Cheap now = expensive later"}'::jsonb),
  (NULL, 'objection', 'Price - Competitor is Cheaper', 'Good research! Quick question though - are they comparing apples to apples? Most cheaper tools require you to still write every message manually. Ours thinks for you. What''s your time worth per hour?', '["price", "competitor"]'::jsonb, '["competitor", "other_tool", "cheaper_option"]'::jsonb, 'all', '{"category": "price", "reframe": "Value comparison, not price comparison"}'::jsonb),
  (NULL, 'objection', 'Price - No Budget', 'I hear you on budget constraints. Here''s a thought - what if this could pay for itself within 30 days by recovering leads you''re currently losing? Could we explore a trial?', '["price", "budget"]'::jsonb, '["no_budget", "zero_budget", "budget_locked"]'::jsonb, 'all', '{"category": "price", "reframe": "Self-funding tool"}'::jsonb),
  (NULL, 'objection', 'Price - Need to Check with Spouse', 'Smart to be aligned at home. When you talk with them, share this: it''s one recovered deal to break even. After that, it''s pure profit. What objections might they have that I can help address?', '["price", "authority"]'::jsonb, '["spouse", "partner", "family"]'::jsonb, 'all', '{"category": "price", "reframe": "Arm them with ROI argument"}'::jsonb),
  (NULL, 'objection', 'Price - Just Looking', 'Totally fair - research mode is smart. What specifically are you looking for in a solution? I can tell you if we''re even the right fit, no pressure.', '["price", "interest"]'::jsonb, '["looking", "researching", "browsing"]'::jsonb, 'all', '{"category": "price", "reframe": "Qualify fit openly"}'::jsonb),
  (NULL, 'objection', 'Price - Need to Think About ROI', 'Love that you think about ROI. Let me make it easy: if you have leads not being followed up within 24 hours, you''re losing money. We fix that. What''s your current follow-up delay?', '["price", "roi"]'::jsonb, '["roi", "return", "investment"]'::jsonb, 'all', '{"category": "price", "reframe": "Quantify current loss"}'::jsonb),
  (NULL, 'objection', 'Price - Payment Plan Needed', 'We can definitely work with that. Most important thing is getting you results. Let''s figure out what works for your cash flow. What payment structure would make this work?', '["price", "payment"]'::jsonb, '["payment_plan", "installments", "monthly"]'::jsonb, 'all', '{"category": "price", "reframe": "Flexible = accessible"}'::jsonb),
  (NULL, 'objection', 'Price - Need Discount', 'I respect the ask. Here''s what I can do - instead of discounting, let me give you extended value: extra month free or premium features. That way you get more, not less. Deal?', '["price", "negotiation"]'::jsonb, '["discount", "deal", "lower_price"]'::jsonb, 'all', '{"category": "price", "reframe": "Add value, don''t reduce price"}'::jsonb),
  (NULL, 'objection', 'Price - Free Trial First', 'I like your thinking. We do offer a trial period. But here''s my experience - people who commit see results 3x faster than those who "try." Want to start with commitment and a money-back guarantee instead?', '["price", "trial"]'::jsonb, '["free_trial", "try_first", "test"]'::jsonb, 'all', '{"category": "price", "reframe": "Commitment drives results"}'::jsonb),
  (NULL, 'objection', 'Price - Wait for Sale', 'Smart shopper! But here''s the thing - every day waiting is leads leaking. Our best "sale" is starting now and recovering deals this month. Make sense?', '["price", "timing"]'::jsonb, '["sale", "discount", "promotion"]'::jsonb, 'all', '{"category": "price", "reframe": "Waiting costs more than savings"}'::jsonb),
  (NULL, 'objection', 'Price - Hidden Fees Concern', 'Great question - transparency matters. There are zero hidden fees. What you see is what you pay. Annual saves you 20%. Want me to break down exactly what''s included?', '["price", "trust"]'::jsonb, '["hidden_fees", "surprise_charges", "total_cost"]'::jsonb, 'all', '{"category": "price", "reframe": "Transparency builds trust"}'::jsonb),
  (NULL, 'objection', 'Price - Already Paying for Similar', 'Understood - budget''s already allocated. Quick thought: if this replaced what you''re paying AND performed better, would that be worth a 15-minute look? We can compare feature-by-feature.', '["price", "existing"]'::jsonb, '["already_paying", "current_tool", "switch"]'::jsonb, 'all', '{"category": "price", "reframe": "Replacement vs addition"}'::jsonb),
  (NULL, 'objection', 'Price - Economy is Bad', 'I feel that. Here''s the counterpoint - when economy is tight, every lead matters MORE. Businesses that automate follow-up thrive while others struggle. Want to recession-proof your sales?', '["price", "economy"]'::jsonb, '["economy", "recession", "market"]'::jsonb, 'all', '{"category": "price", "reframe": "Tough times = automation essential"}'::jsonb),
  (NULL, 'objection', 'Price - Company Budget Freeze', 'Budget freezes are real. But here''s the workaround - this tool often pays for itself in marketing efficiency gains. Could we frame it as cost savings rather than new expense?', '["price", "corporate"]'::jsonb, '["budget_freeze", "corporate", "approved"]'::jsonb, 'all', '{"category": "price", "reframe": "Reframe as savings"}'::jsonb),
  (NULL, 'objection', 'Price - Small Business Budget', 'I get it - small budgets mean big decisions. That''s actually who we built this for. The Starter plan is designed to get you profitable before you scale up. Want to see it?', '["price", "small_business"]'::jsonb, '["small_business", "limited_budget", "startup"]'::jsonb, 'all', '{"category": "price", "reframe": "Built for small budgets"}'::jsonb),
  (NULL, 'objection', 'Price - Need Board Approval', 'Smart governance. What would your board need to see to approve? I can help you build the business case - ROI projections, risk mitigation, competitive advantage. Would that help?', '["price", "authority"]'::jsonb, '["board", "approval", "committee"]'::jsonb, 'all', '{"category": "price", "reframe": "Help build their case"}'::jsonb),
  (NULL, 'objection', 'Price - What If It Doesn''t Work', 'Valid concern. That''s why we have a 30-day guarantee - if you don''t see results, you don''t pay. The risk is entirely on us. Fair enough?', '["price", "risk"]'::jsonb, '["not_work", "guarantee", "refund"]'::jsonb, 'all', '{"category": "price", "reframe": "Remove risk completely"}'::jsonb),
  (NULL, 'objection', 'Price - Subscription Fatigue', 'I hear you - subscriptions add up. But this isn''t another tool that sits unused. It actively makes you money every day. Which subscriptions are making you money vs. costing you?', '["price", "fatigue"]'::jsonb, '["subscription", "monthly_fee", "saas"]'::jsonb, 'all', '{"category": "price", "reframe": "Revenue tool vs expense tool"}'::jsonb)
ON CONFLICT DO NOTHING;

-- TRUST OBJECTIONS (15 entries)
INSERT INTO content_library (user_id, type, name, content, intent_tags, objection_tags, channel_restriction, metadata)
VALUES
  (NULL, 'objection', 'Trust - Need More Proof', 'Totally fair. Would case studies help? I can share how [similar business] went from missing 60% of leads to converting 35% more within 60 days. Want me to send that over?', '["trust", "proof"]'::jsonb, '["proof", "evidence", "show_me"]'::jsonb, 'all', '{"category": "trust", "reframe": "Social proof addresses doubt"}'::jsonb),
  (NULL, 'objection', 'Trust - Is This Legit', 'Great question - healthy skepticism is smart. We''ve been doing this for [X] years, work with [Y] businesses, and have a 4.8 star rating. Want to see reviews from people in your industry?', '["trust", "credibility"]'::jsonb, '["legit", "scam", "real"]'::jsonb, 'all', '{"category": "trust", "reframe": "Credentials build credibility"}'::jsonb),
  (NULL, 'objection', 'Trust - Never Heard of You', 'That''s okay! We focus on results, not marketing hype. Many of our best users found us through referrals. Would it help to connect you with a current user in your space?', '["trust", "awareness"]'::jsonb, '["never_heard", "unknown", "new"]'::jsonb, 'all', '{"category": "trust", "reframe": "Results over fame"}'::jsonb),
  (NULL, 'objection', 'Trust - Need References', 'Absolutely - I''d be suspicious if you didn''t ask. I can connect you with 3 users in similar businesses. What industry are you in so I can match you properly?', '["trust", "social_proof"]'::jsonb, '["references", "testimonials", "customers"]'::jsonb, 'all', '{"category": "trust", "reframe": "Provide specific references"}'::jsonb),
  (NULL, 'objection', 'Trust - Sounds Too Good', 'Ha! I get that a lot. Here''s the thing - it''s not magic, it''s math. Follow up faster = more conversions. We just automate what works. Can I show you the logic?', '["trust", "skepticism"]'::jsonb, '["too_good", "skeptical", "unrealistic"]'::jsonb, 'all', '{"category": "trust", "reframe": "Logic over hype"}'::jsonb),
  (NULL, 'objection', 'Trust - Bad Experience Before', 'I''m sorry you went through that. Mind sharing what went wrong? I want to make sure we''re different - and if we''re not the right fit, I''ll tell you honestly.', '["trust", "past_experience"]'::jsonb, '["bad_experience", "burned", "disappointed"]'::jsonb, 'all', '{"category": "trust", "reframe": "Acknowledge and differentiate"}'::jsonb),
  (NULL, 'objection', 'Trust - Is My Data Safe', 'Critical question. We''re SOC 2 compliant, use bank-level encryption, and never sell data. You own everything. Want me to send our security documentation?', '["trust", "security"]'::jsonb, '["data", "privacy", "security"]'::jsonb, 'all', '{"category": "trust", "reframe": "Security specifics build trust"}'::jsonb),
  (NULL, 'objection', 'Trust - Will You Be Around', 'Fair concern with any company. We''ve been growing 40% year over year, profitable, and backed by [investors]. But more important - your data is always exportable. No lock-in.', '["trust", "stability"]'::jsonb, '["around", "future", "stable"]'::jsonb, 'all', '{"category": "trust", "reframe": "Growth + portability = trust"}'::jsonb),
  (NULL, 'objection', 'Trust - Who Else Uses This', 'Good question! We work with coaches, agencies, consultants, and service businesses. Our sweet spot is anyone with high-ticket offers. What do you sell?', '["trust", "validation"]'::jsonb, '["who_uses", "customers", "market"]'::jsonb, 'all', '{"category": "trust", "reframe": "Industry fit validation"}'::jsonb),
  (NULL, 'objection', 'Trust - This Seems Complicated', 'I can see why it might look that way. Reality: setup is 10 minutes, then it''s mostly hands-off. We even have done-for-you setup. Want me to walk you through it?', '["trust", "complexity"]'::jsonb, '["complicated", "technical", "difficult"]'::jsonb, 'all', '{"category": "trust", "reframe": "Simple setup + support"}'::jsonb),
  (NULL, 'objection', 'Trust - AI Makes Me Nervous', 'I understand - AI can feel weird. Here''s how we use it: AI suggests, you approve. Nothing sends without your review if you want. Full control. Feel better?', '["trust", "ai"]'::jsonb, '["ai", "artificial", "robot"]'::jsonb, 'all', '{"category": "trust", "reframe": "AI assists, human controls"}'::jsonb),
  (NULL, 'objection', 'Trust - Need to Do Research', 'Absolutely support that. Here''s what I''d look for: results vs promises, support quality, actual user reviews, and whether they guarantee results. Want a comparison checklist?', '["trust", "research"]'::jsonb, '["research", "compare", "due_diligence"]'::jsonb, 'all', '{"category": "trust", "reframe": "Help their research"}'::jsonb),
  (NULL, 'objection', 'Trust - Friend Had Issues', 'Oh no - what happened? I''d genuinely like to know so I can either explain what might have gone wrong or acknowledge a real issue. Transparency matters to me.', '["trust", "word_of_mouth"]'::jsonb, '["friend", "heard", "someone_said"]'::jsonb, 'all', '{"category": "trust", "reframe": "Address specific concern"}'::jsonb),
  (NULL, 'objection', 'Trust - Why Should I Trust You', 'Honestly? You shouldn''t trust me yet - trust is earned. Here''s what I can offer: a trial period, money-back guarantee, and real references. Let me earn your trust.', '["trust", "personal"]'::jsonb, '["trust_you", "believe", "faith"]'::jsonb, 'all', '{"category": "trust", "reframe": "Humble + actionable trust-building"}'::jsonb),
  (NULL, 'objection', 'Trust - Seen Fake Reviews', 'Smart to be skeptical. Our reviews are on third-party platforms you can verify - G2, Capterra, Trustpilot. Can''t fake those. Want the links?', '["trust", "reviews"]'::jsonb, '["fake_reviews", "reviews", "ratings"]'::jsonb, 'all', '{"category": "trust", "reframe": "Third-party verification"}'::jsonb)
ON CONFLICT DO NOTHING;

-- AUTHORITY OBJECTIONS (15 entries)
INSERT INTO content_library (user_id, type, name, content, intent_tags, objection_tags, channel_restriction, metadata)
VALUES
  (NULL, 'objection', 'Authority - Need to Ask Partner', 'Of course - important decisions should be made together. What concerns do you think they might have? I can help you address those proactively.', '["authority", "partner"]'::jsonb, '["partner", "spouse", "other_half"]'::jsonb, 'all', '{"category": "authority", "reframe": "Anticipate their concerns"}'::jsonb),
  (NULL, 'objection', 'Authority - Not the Decision Maker', 'Got it. Who else is involved in the decision? I''d be happy to include them in our next conversation, or help you build a compelling case to present.', '["authority", "role"]'::jsonb, '["decision_maker", "not_me", "someone_else"]'::jsonb, 'all', '{"category": "authority", "reframe": "Include decision maker"}'::jsonb),
  (NULL, 'objection', 'Authority - Boss Needs to Approve', 'Totally understand. What does your boss typically look for in tool purchases? ROI? Ease of use? I can tailor info that speaks directly to their priorities.', '["authority", "manager"]'::jsonb, '["boss", "manager", "supervisor"]'::jsonb, 'all', '{"category": "authority", "reframe": "Customize for their boss"}'::jsonb),
  (NULL, 'objection', 'Authority - Need Team Buy-In', 'Smart approach. Team adoption is key. Would it help if I did a brief demo for the team? Usually takes 15 minutes and answers everyone''s questions at once.', '["authority", "team"]'::jsonb, '["team", "colleagues", "staff"]'::jsonb, 'all', '{"category": "authority", "reframe": "Offer team demo"}'::jsonb),
  (NULL, 'objection', 'Authority - Board Decides', 'Board-level decisions require solid data. I can help you build a presentation with ROI projections, risk analysis, and competitive positioning. Would that be useful?', '["authority", "governance"]'::jsonb, '["board", "directors", "committee"]'::jsonb, 'all', '{"category": "authority", "reframe": "Enable their presentation"}'::jsonb),
  (NULL, 'objection', 'Authority - Procurement Process', 'Understood - processes exist for good reason. What''s typically required? Vendor forms, security reviews, pricing comparisons? I''ve been through many of these and can expedite.', '["authority", "process"]'::jsonb, '["procurement", "process", "paperwork"]'::jsonb, 'all', '{"category": "authority", "reframe": "Streamline their process"}'::jsonb),
  (NULL, 'objection', 'Authority - Legal Review Needed', 'Of course. Our legal team is used to working with enterprise clients. I can send our standard agreement and security documentation today. What''s the typical review timeline?', '["authority", "legal"]'::jsonb, '["legal", "contract", "review"]'::jsonb, 'all', '{"category": "authority", "reframe": "Expedite legal review"}'::jsonb),
  (NULL, 'objection', 'Authority - Need CFO Sign-Off', 'CFOs love ROI. I can provide a financial impact analysis showing payback period and projected returns. Would a one-pager work for your CFO?', '["authority", "finance"]'::jsonb, '["cfo", "finance", "accounting"]'::jsonb, 'all', '{"category": "authority", "reframe": "Speak CFO language"}'::jsonb),
  (NULL, 'objection', 'Authority - IT Needs to Vet', 'Absolutely - security is critical. We''re SOC 2 certified and I can fast-track a call with our security team. When could IT be available for a 20-minute security review?', '["authority", "it"]'::jsonb, '["it", "tech_team", "security"]'::jsonb, 'all', '{"category": "authority", "reframe": "Facilitate IT review"}'::jsonb),
  (NULL, 'objection', 'Authority - Marketing Controls Budget', 'Perfect - I can frame this as marketing efficiency. Less manual follow-up, more conversions, better lead ROI. Should we set up a call with your marketing lead?', '["authority", "marketing"]'::jsonb, '["marketing", "budget", "department"]'::jsonb, 'all', '{"category": "authority", "reframe": "Marketing value prop"}'::jsonb),
  (NULL, 'objection', 'Authority - Franchise Decision', 'Corporate decisions can be slower, but individual location success often influences the group. Would starting with your location as a pilot make sense?', '["authority", "franchise"]'::jsonb, '["franchise", "corporate", "headquarters"]'::jsonb, 'all', '{"category": "authority", "reframe": "Pilot at your location"}'::jsonb),
  (NULL, 'objection', 'Authority - Co-Founder Disagrees', 'Founder alignment is crucial. What specifically concerns your co-founder? Sometimes the hesitation reveals a valid concern worth addressing - or a misunderstanding I can clarify.', '["authority", "cofounder"]'::jsonb, '["cofounder", "partner", "business_partner"]'::jsonb, 'all', '{"category": "authority", "reframe": "Address specific concerns"}'::jsonb),
  (NULL, 'objection', 'Authority - Stakeholders Uninformed', 'Let''s fix that. I can create a stakeholder briefing document covering key benefits, risks, and implementation plan. Would that help move things forward?', '["authority", "stakeholders"]'::jsonb, '["stakeholders", "executives", "leadership"]'::jsonb, 'all', '{"category": "authority", "reframe": "Create briefing materials"}'::jsonb),
  (NULL, 'objection', 'Authority - Committee Review Required', 'Committees can be thorough. I''ve helped many clients navigate committee reviews - what format works best? Presentation, document, live demo?', '["authority", "committee"]'::jsonb, '["committee", "group", "review_board"]'::jsonb, 'all', '{"category": "authority", "reframe": "Format for their process"}'::jsonb),
  (NULL, 'objection', 'Authority - Policy Against New Tools', 'Policies exist for good reasons. But often there''s an exception process for tools with proven ROI. Who would grant an exception, and what would they need to see?', '["authority", "policy"]'::jsonb, '["policy", "rules", "restrictions"]'::jsonb, 'all', '{"category": "authority", "reframe": "Find the exception path"}'::jsonb)
ON CONFLICT DO NOTHING;

-- FIT OBJECTIONS (15 entries)
INSERT INTO content_library (user_id, type, name, content, intent_tags, objection_tags, channel_restriction, metadata)
VALUES
  (NULL, 'objection', 'Fit - Not for My Industry', 'I hear that often, and I get it. Can I ask what industry you''re in? I may have case studies from similar businesses, or I''ll honestly tell you if we''re not the right fit.', '["fit", "industry"]'::jsonb, '["industry", "niche", "sector"]'::jsonb, 'all', '{"category": "fit", "reframe": "Show relevant examples or be honest"}'::jsonb),
  (NULL, 'objection', 'Fit - Too Small for This', 'Actually, you might be the perfect size. Small teams benefit most from automation - it''s like having 5 extra employees without the payroll. How many leads do you handle weekly?', '["fit", "size"]'::jsonb, '["too_small", "small_business", "startup"]'::jsonb, 'all', '{"category": "fit", "reframe": "Small = perfect for automation"}'::jsonb),
  (NULL, 'objection', 'Fit - Too Big for This', 'I understand - enterprise has different needs. We do have enterprise clients with custom integrations. Would it help to discuss your specific scale requirements?', '["fit", "enterprise"]'::jsonb, '["too_big", "enterprise", "large_company"]'::jsonb, 'all', '{"category": "fit", "reframe": "Custom enterprise solutions"}'::jsonb),
  (NULL, 'objection', 'Fit - Already Have a System', 'Great - systems are important. I''m curious though - is it fully automated? Most "systems" still require manual work. Ours runs 24/7 without you. What does yours require?', '["fit", "existing"]'::jsonb, '["already_have", "current_system", "using_something"]'::jsonb, 'all', '{"category": "fit", "reframe": "Question automation level"}'::jsonb),
  (NULL, 'objection', 'Fit - Don''t Get Enough Leads', 'That''s actually the perfect time to set this up - when leads ARE coming, you''ll be ready. Plus, we help you re-engage cold leads you already have. How many contacts are in your database?', '["fit", "volume"]'::jsonb, '["not_enough_leads", "low_volume", "few_leads"]'::jsonb, 'all', '{"category": "fit", "reframe": "Prepare + reactivate existing leads"}'::jsonb),
  (NULL, 'objection', 'Fit - B2B Not B2C', 'We''re actually stronger in B2B! Longer sales cycles benefit most from persistent, intelligent follow-up. B2B is exactly where we shine. What''s your typical sales cycle length?', '["fit", "market"]'::jsonb, '["b2b", "business_to_business", "enterprise_sales"]'::jsonb, 'all', '{"category": "fit", "reframe": "B2B is our strength"}'::jsonb),
  (NULL, 'objection', 'Fit - Local Business Only', 'Local businesses are our specialty! You need every lead to count. One recovered local customer can be worth thousands in lifetime value. How much is a customer worth to you?', '["fit", "local"]'::jsonb, '["local", "small_town", "regional"]'::jsonb, 'all', '{"category": "fit", "reframe": "Local = every lead matters more"}'::jsonb),
  (NULL, 'objection', 'Fit - Service-Based Model', 'Perfect - service businesses are our core users. High-ticket services need relationship building, which is exactly what intelligent follow-up creates. Tell me about your services.', '["fit", "service"]'::jsonb, '["service", "consulting", "professional"]'::jsonb, 'all', '{"category": "fit", "reframe": "Built for services"}'::jsonb),
  (NULL, 'objection', 'Fit - One-Person Operation', 'Solo operators benefit most from automation - it''s like cloning yourself. You handle delivery while we handle follow-up. Want to see how other solopreneurs use it?', '["fit", "solo"]'::jsonb, '["solo", "one_person", "freelancer"]'::jsonb, 'all', '{"category": "fit", "reframe": "Clone yourself with automation"}'::jsonb),
  (NULL, 'objection', 'Fit - Physical Products', 'Product businesses have complex follow-up needs - cart abandonment, post-purchase sequences, review requests. We handle all of that. What''s your current cart abandonment rate?', '["fit", "ecommerce"]'::jsonb, '["products", "ecommerce", "physical_goods"]'::jsonb, 'all', '{"category": "fit", "reframe": "E-commerce sequences covered"}'::jsonb),
  (NULL, 'objection', 'Fit - Seasonal Business', 'Seasonal businesses need to maximize every opportunity in peak season. We help you nurture off-season leads so they''re ready when you are. When''s your peak?', '["fit", "seasonal"]'::jsonb, '["seasonal", "cyclical", "peak_season"]'::jsonb, 'all', '{"category": "fit", "reframe": "Maximize peak + nurture off-season"}'::jsonb),
  (NULL, 'objection', 'Fit - Technical Integration', 'We integrate with most tools - CRMs, email platforms, schedulers. What are you currently using? I can confirm compatibility in 30 seconds.', '["fit", "technical"]'::jsonb, '["integration", "api", "compatibility"]'::jsonb, 'all', '{"category": "fit", "reframe": "Quick compatibility check"}'::jsonb),
  (NULL, 'objection', 'Fit - Complex Sales Process', 'Complex processes benefit most from automation - multiple touchpoints, decision makers, long cycles. We''re built for complexity. Walk me through your process?', '["fit", "complexity"]'::jsonb, '["complex", "long_cycle", "multiple_steps"]'::jsonb, 'all', '{"category": "fit", "reframe": "Built for complexity"}'::jsonb),
  (NULL, 'objection', 'Fit - Different Business Model', 'I appreciate the honesty. Tell me more about your model - I want to understand if we can help or should bow out gracefully. What makes your model unique?', '["fit", "model"]'::jsonb, '["different", "unique", "unusual"]'::jsonb, 'all', '{"category": "fit", "reframe": "Explore fit openly"}'::jsonb),
  (NULL, 'objection', 'Fit - International Customers', 'Global reach is no problem - we support multiple languages, timezones, and currencies. Where are your customers located? I can show relevant features.', '["fit", "international"]'::jsonb, '["international", "global", "overseas"]'::jsonb, 'all', '{"category": "fit", "reframe": "Global capabilities"}'::jsonb)
ON CONFLICT DO NOTHING;

-- COMPETITOR OBJECTIONS (15 entries)
INSERT INTO content_library (user_id, type, name, content, intent_tags, objection_tags, channel_restriction, metadata)
VALUES
  (NULL, 'objection', 'Competitor - Using X Already', 'Totally get loyalty to what works. Quick question - is X handling your follow-up automatically, or are you still writing messages manually? That''s the key difference we offer.', '["competitor", "existing"]'::jsonb, '["using", "already_have", "competitor_name"]'::jsonb, 'all', '{"category": "competitor", "reframe": "Automation vs manual distinction"}'::jsonb),
  (NULL, 'objection', 'Competitor - X is Cheaper', 'Price is one factor. But what''s your time worth? If X requires manual work and we don''t, the true cost comparison changes. How many hours weekly on follow-up currently?', '["competitor", "price"]'::jsonb, '["cheaper", "less_expensive", "lower_cost"]'::jsonb, 'all', '{"category": "competitor", "reframe": "Total cost including time"}'::jsonb),
  (NULL, 'objection', 'Competitor - Switching Costs', 'I understand - switching is work. Here''s the thing: we handle migration. Your data imports in minutes, and we''ll even help you transition sequences. No heavy lifting for you.', '["competitor", "switching"]'::jsonb, '["switching", "migration", "moving"]'::jsonb, 'all', '{"category": "competitor", "reframe": "We handle the switch"}'::jsonb),
  (NULL, 'objection', 'Competitor - Friend Recommends X', 'Friend recommendations carry weight. But what works for them might not work for you. Different business, different needs. Can I show you how we compare for YOUR use case?', '["competitor", "referral"]'::jsonb, '["friend", "recommended", "told_me"]'::jsonb, 'all', '{"category": "competitor", "reframe": "Your needs are unique"}'::jsonb),
  (NULL, 'objection', 'Competitor - Industry Standard is X', 'Industry standard doesn''t mean industry best. Standards evolve. The question is: does the standard solve YOUR problem optimally? Let''s compare on your specific needs.', '["competitor", "standard"]'::jsonb, '["standard", "everyone_uses", "common"]'::jsonb, 'all', '{"category": "competitor", "reframe": "Standard ≠ best for you"}'::jsonb),
  (NULL, 'objection', 'Competitor - X Has More Features', 'More features often means more complexity. Do you use all of X''s features? Most people use 20% and pay for 100%. We focus on what actually drives results.', '["competitor", "features"]'::jsonb, '["more_features", "capabilities", "options"]'::jsonb, 'all', '{"category": "competitor", "reframe": "Right features > more features"}'::jsonb),
  (NULL, 'objection', 'Competitor - X Has Better Support', 'Support is critical - we agree. Our average response time is under 4 hours, and you get a dedicated success manager. What support has been lacking for you?', '["competitor", "support"]'::jsonb, '["support", "help", "customer_service"]'::jsonb, 'all', '{"category": "competitor", "reframe": "Highlight our support quality"}'::jsonb),
  (NULL, 'objection', 'Competitor - Contract with X', 'Contracts can feel like handcuffs. When does yours end? We can do a parallel test so you''re ready to switch when you''re free. No commitment until you choose.', '["competitor", "contract"]'::jsonb, '["contract", "locked_in", "agreement"]'::jsonb, 'all', '{"category": "competitor", "reframe": "Plan for contract end"}'::jsonb),
  (NULL, 'objection', 'Competitor - X Integrates Better', 'Integration is key - I agree. What tools do you need to integrate with? I can confirm our capabilities right now. We integrate with 50+ platforms.', '["competitor", "integration"]'::jsonb, '["integrates", "connects", "works_with"]'::jsonb, 'all', '{"category": "competitor", "reframe": "Verify integration needs"}'::jsonb),
  (NULL, 'objection', 'Competitor - Invested in X Training', 'Training investment is real. Good news: our learning curve is under 30 minutes. Most users are productive same-day. Would a demo show you how simple it is?', '["competitor", "training"]'::jsonb, '["trained", "learned", "invested_time"]'::jsonb, 'all', '{"category": "competitor", "reframe": "Our learning curve is shorter"}'::jsonb),
  (NULL, 'objection', 'Competitor - X Has Market Share', 'Market share is one metric. But the fastest-growing businesses often adopt newer, better solutions before they''re mainstream. Early adopters win. Want to be one?', '["competitor", "market"]'::jsonb, '["market_share", "popular", "leader"]'::jsonb, 'all', '{"category": "competitor", "reframe": "Early adopters advantage"}'::jsonb),
  (NULL, 'objection', 'Competitor - Tried Something Similar', 'I appreciate the context. What specifically didn''t work before? I want to either address that directly or tell you if we have the same limitation.', '["competitor", "past"]'::jsonb, '["tried", "similar", "before"]'::jsonb, 'all', '{"category": "competitor", "reframe": "Learn from past experience"}'::jsonb),
  (NULL, 'objection', 'Competitor - X Was Recommended by Expert', 'Experts are valuable. But experts often get paid to recommend certain tools. What criteria did the expert use? Let''s evaluate on YOUR priorities, not theirs.', '["competitor", "expert"]'::jsonb, '["expert", "influencer", "recommended"]'::jsonb, 'all', '{"category": "competitor", "reframe": "Your criteria matter most"}'::jsonb),
  (NULL, 'objection', 'Competitor - Building In-House', 'Building is tempting when you have dev resources. But here''s the math: our cost vs. developer time + maintenance + opportunity cost. How long until your build is ready?', '["competitor", "diy"]'::jsonb, '["building", "in_house", "internal"]'::jsonb, 'all', '{"category": "competitor", "reframe": "Buy vs build economics"}'::jsonb),
  (NULL, 'objection', 'Competitor - Waiting for X''s New Version', 'Waiting for updates is smart for some things. But for business tools, every day waiting is leads lost. What if you started now and switched later IF their update is better?', '["competitor", "waiting"]'::jsonb, '["waiting", "new_version", "update"]'::jsonb, 'all', '{"category": "competitor", "reframe": "Start now, decide later"}'::jsonb)
ON CONFLICT DO NOTHING;

-- DECISION OBJECTIONS (15 entries - close to yes, need final push)
INSERT INTO content_library (user_id, type, name, content, intent_tags, objection_tags, channel_restriction, metadata)
VALUES
  (NULL, 'objection', 'Decision - Let Me Sleep On It', 'Absolutely - sleep on it. But here''s a thought: what specifically needs to settle overnight? If we can address it now, you wake up to a decision already made.', '["decision", "delay"]'::jsonb, '["sleep_on_it", "think_about_it", "overnight"]'::jsonb, 'all', '{"category": "decision", "reframe": "Surface the real hesitation"}'::jsonb),
  (NULL, 'objection', 'Decision - Almost Convinced', 'That''s great to hear! What''s the one thing that would take you from almost to absolutely? I want to address that directly.', '["decision", "close"]'::jsonb, '["almost", "nearly", "getting_there"]'::jsonb, 'all', '{"category": "decision", "reframe": "Identify final hurdle"}'::jsonb),
  (NULL, 'objection', 'Decision - Need One More Thing', 'You''ve done your homework. What''s that one thing? I''ll either provide it or explain why it''s not needed. Either way, you''ll have clarity.', '["decision", "information"]'::jsonb, '["one_more", "need_info", "clarify"]'::jsonb, 'all', '{"category": "decision", "reframe": "Provide or explain"}'::jsonb),
  (NULL, 'objection', 'Decision - So Close to Yes', 'I can feel it! What''s holding you back? Often at this point, it''s just fear of change - which is normal. But the cost of not changing is usually higher.', '["decision", "fear"]'::jsonb, '["close", "almost_yes", "on_the_fence"]'::jsonb, 'all', '{"category": "decision", "reframe": "Name the fear"}'::jsonb),
  (NULL, 'objection', 'Decision - What If I Regret It', 'Valid concern. But consider this: you''re more likely to regret NOT trying than trying and learning. Plus, we have a money-back guarantee. What''s the worst case?', '["decision", "regret"]'::jsonb, '["regret", "mistake", "wrong_decision"]'::jsonb, 'all', '{"category": "decision", "reframe": "Regret of inaction > regret of action"}'::jsonb),
  (NULL, 'objection', 'Decision - Last Question', 'I love last questions - means you''re ready. Ask away, and once answered, are you ready to move forward?', '["decision", "close"]'::jsonb, '["last_question", "final", "one_more"]'::jsonb, 'all', '{"category": "decision", "reframe": "Confirm close after answer"}'::jsonb),
  (NULL, 'objection', 'Decision - Still Comparing', 'Smart to compare. What''s your comparison criteria? I can show you exactly how we stack up on the factors that matter most to you.', '["decision", "comparison"]'::jsonb, '["comparing", "options", "evaluating"]'::jsonb, 'all', '{"category": "decision", "reframe": "Win the comparison"}'::jsonb),
  (NULL, 'objection', 'Decision - Just Not Sure', 'Uncertainty is uncomfortable. Let''s break it down: what are you unsure about specifically? We can tackle each piece until you have clarity.', '["decision", "uncertainty"]'::jsonb, '["not_sure", "uncertain", "maybe"]'::jsonb, 'all', '{"category": "decision", "reframe": "Break down the uncertainty"}'::jsonb),
  (NULL, 'objection', 'Decision - Need to See It Work', 'Seeing is believing. Want a personalized demo with YOUR use case? Or better - start a trial and see results yourself within 7 days.', '["decision", "proof"]'::jsonb, '["see_it", "demo", "proof"]'::jsonb, 'all', '{"category": "decision", "reframe": "Offer personalized proof"}'::jsonb),
  (NULL, 'objection', 'Decision - Gut Says Wait', 'I respect gut feelings. But here''s a question: is your gut protecting you from something real, or just protecting you from change? What is it sensing?', '["decision", "intuition"]'::jsonb, '["gut", "feeling", "instinct"]'::jsonb, 'all', '{"category": "decision", "reframe": "Examine the gut feeling"}'::jsonb),
  (NULL, 'objection', 'Decision - Can I Start Later', 'You can - we''ll be here. But leads won''t wait. Every day without automated follow-up is opportunities lost. What''s the benefit of waiting?', '["decision", "delay"]'::jsonb, '["start_later", "next_month", "future"]'::jsonb, 'all', '{"category": "decision", "reframe": "Cost of waiting"}'::jsonb),
  (NULL, 'objection', 'Decision - Promise Me It Works', 'I can''t promise specific results - that depends on many factors. But I can promise: our guarantee means if you don''t see value, you don''t pay. Zero risk.', '["decision", "guarantee"]'::jsonb, '["promise", "guarantee", "assure"]'::jsonb, 'all', '{"category": "decision", "reframe": "Guarantee addresses risk"}'::jsonb),
  (NULL, 'objection', 'Decision - Feels Like Big Step', 'It is a step - but not as big as you think. Setup is 10 minutes, not 10 hours. Start small, see results, then expand. How about we begin with just email follow-up?', '["decision", "overwhelm"]'::jsonb, '["big_step", "commitment", "major"]'::jsonb, 'all', '{"category": "decision", "reframe": "Start small"}'::jsonb),
  (NULL, 'objection', 'Decision - What If Needs Change', 'Needs always change. That''s why we''re flexible - upgrade, downgrade, or cancel anytime. You''re never locked into something that doesn''t fit.', '["decision", "flexibility"]'::jsonb, '["needs_change", "future", "locked_in"]'::jsonb, 'all', '{"category": "decision", "reframe": "Flexibility built in"}'::jsonb),
  (NULL, 'objection', 'Decision - Ready But Scared', 'Fear before big decisions is normal - it means you care. Here''s what I know: action beats fear. Take the step, and the fear transforms into excitement. Ready?', '["decision", "fear"]'::jsonb, '["scared", "nervous", "afraid"]'::jsonb, 'all', '{"category": "decision", "reframe": "Action beats fear"}'::jsonb)
ON CONFLICT DO NOTHING;
